#!/bin/bash -f
#**********************************************************************************************************
# Vivado (TM) v2023.2 (64-bit)
#
# Script generated by Vivado on Thu Mar 21 19:01:48 -0400 2024
# SW Build 4029153 on Fri Oct 13 20:14:34 MDT 2023
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved. 
#
# Filename     : rfdc_ex.sh
# Simulator    : Cadence Xcelium Parallel Simulator
# Description  : Simulation script generated by export_simulation Tcl command
# Purpose      : Run 'compile', 'elaborate', 'simulate' steps for compiling, elaborating and simulating the
#                design. The script will copy the library mapping file from the compiled library directory,
#                create design library directories and library mappings in the mapping file.
#
# Usage        : rfdc_ex.sh
#                rfdc_ex.sh [-lib_map_path] [-step] [-keep_index] [-noclean_files]*
#                rfdc_ex.sh [-reset_run]
#                rfdc_ex.sh [-reset_log]
#                rfdc_ex.sh [-help]
#
#               * The -noclean_files switch is deprecated and will not peform any function (by default, the
#                 simulator generated files will not be removed unless -reset_run switch is used)
#
# Prerequisite : Before running export_simulation, you must first compile the AMD simulation library
#                using the 'compile_simlib' Tcl command (for more information, run 'compile_simlib -help'
#                command in the Vivado Tcl shell). After compiling the library, specify the -lib_map_path
#                switch with the directory path where the library is created while generating the script
#                with export_simulation.
#
#                Alternatively, you can set the library path by setting the following project property:-
#
#                 set_property compxlib.<simulator>_compiled_library_dir <path> [current_project]
#
#                You can also point to the simulation library by either setting the 'lib_map_path' global
#                variable in this script or specify it with the '-lib_map_path' switch while executing this
#                script (type 'rfdc_ex.sh -help' for more information).
#
#                Note: For pure RTL based designs, the -lib_map_path switch can be specified later with the
#                generated script, but if design is targetted for system simulation containing SystemC/C++/C
#                sources, then the library path MUST be specified upfront when calling export_simulation.
#
#                For more information, refer 'Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#**********************************************************************************************************

# catch pipeline exit status
set -Eeuo pipefail

# set xmvhdl compile options
xmvhdl_opts="-64bit -messages -logfile .tmp_log -update"

# set xmvlog compile options
xmvlog_opts="-64bit -messages -logfile .tmp_log -update"

# set xmelab elaboration options
xmelab_opts="-64bit -relax -access +rwc -namemap_mixgen -messages -logfile elaborate.log"

# set xmsim simulation options
xmsim_opts="-64bit -logfile simulate.log"

# set design libraries for elaboration
design_libs_elab="-libname xilinx_vip -libname xpm -libname xil_defaultlib -libname xlconstant_v1_1_8 -libname lib_cdc_v1_0_2 -libname proc_sys_reset_v5_0_14 -libname smartconnect_v1_0 -libname axi_infrastructure_v1_1_0 -libname axi_register_slice_v2_1_29 -libname axi_vip_v1_1_15 -libname jtag_axi -libname microblaze_v11_0_12 -libname axi_lite_ipif_v3_0_4 -libname mdm_v3_2_25 -libname lmb_bram_if_cntlr_v4_0_23 -libname lmb_v10_v3_0_13 -libname blk_mem_gen_v8_4_7 -libname xilinx_vip -libname unisims_ver -libname unimacro_ver -libname secureip"

# set design libraries
design_libs=(simprims_ver xilinx_vip xpm xil_defaultlib xlconstant_v1_1_8 lib_cdc_v1_0_2 proc_sys_reset_v5_0_14 smartconnect_v1_0 axi_infrastructure_v1_1_0 axi_register_slice_v2_1_29 axi_vip_v1_1_15 jtag_axi microblaze_v11_0_12 axi_lite_ipif_v3_0_4 mdm_v3_2_25 lmb_bram_if_cntlr_v4_0_23 lmb_v10_v3_0_13 blk_mem_gen_v8_4_7)

# simulation root library directory
sim_lib_dir="xcelium_lib"

# script info
echo -e "rfdc_ex.sh - Script generated by export_simulation (Vivado v2023.2 (64-bit)-id)\n"

# main steps
run()
{
  check_args $*
  setup
  if [[ ($b_step == 1) ]]; then
    case $step in
      "compile" )
       init_lib
       compile
      ;;
      "elaborate" )
       elaborate
      ;;
      "simulate" )
       simulate
      ;;
      * )
        echo -e "ERROR: Invalid or missing step '$step' (type \"./rfdc_ex.sh -help\" for more information)\n"
        exit 1
      esac
  else
    init_lib
    compile
    elaborate
    simulate
  fi
}

# RUN_STEP: <compile>
compile()
{
  xmvlog -work xilinx_vip $xmvlog_opts -sv +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/f0b6/hdl/verilog" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/35de/hdl/verilog" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/ec67/hdl" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/c2c6" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/e2ba/hdl/verilog" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/a29c/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "C:/Xilinx/Vivado/2023.2/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
  "C:/Xilinx/Vivado/2023.2/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
  "C:/Xilinx/Vivado/2023.2/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
  "C:/Xilinx/Vivado/2023.2/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
  "C:/Xilinx/Vivado/2023.2/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
  "C:/Xilinx/Vivado/2023.2/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
  "C:/Xilinx/Vivado/2023.2/data/xilinx_vip/hdl/axi_vip_if.sv" \
  "C:/Xilinx/Vivado/2023.2/data/xilinx_vip/hdl/clk_vip_if.sv" \
  "C:/Xilinx/Vivado/2023.2/data/xilinx_vip/hdl/rst_vip_if.sv" \
  2>&1 | tee compile.log; cat .tmp_log > xmvlog.log 2>/dev/null

  xmvlog -work xpm $xmvlog_opts -sv +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/f0b6/hdl/verilog" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/35de/hdl/verilog" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/ec67/hdl" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/c2c6" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/e2ba/hdl/verilog" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/a29c/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "C:/Xilinx/Vivado/2023.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
  "C:/Xilinx/Vivado/2023.2/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv" \
  "C:/Xilinx/Vivado/2023.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work xpm $xmvhdl_opts \
  "C:/Xilinx/Vivado/2023.2/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log > xmvhdl.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/f0b6/hdl/verilog" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/35de/hdl/verilog" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/ec67/hdl" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/c2c6" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/e2ba/hdl/verilog" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/a29c/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../bd/rfdc_ex/ip/rfdc_ex_smartconnect_0_0/bd_0/sim/bd_a15e.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xlconstant_v1_1_8 $xmvlog_opts +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/f0b6/hdl/verilog" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/35de/hdl/verilog" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/ec67/hdl" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/c2c6" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/e2ba/hdl/verilog" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/a29c/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/d390/hdl/xlconstant_v1_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/f0b6/hdl/verilog" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/35de/hdl/verilog" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/ec67/hdl" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/c2c6" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/e2ba/hdl/verilog" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/a29c/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../bd/rfdc_ex/ip/rfdc_ex_smartconnect_0_0/bd_0/ip/ip_0/sim/bd_a15e_one_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work lib_cdc_v1_0_2 $xmvhdl_opts \
  "../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work proc_sys_reset_v5_0_14 $xmvhdl_opts \
  "../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/408c/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work xil_defaultlib $xmvhdl_opts \
  "../../../bd/rfdc_ex/ip/rfdc_ex_smartconnect_0_0/bd_0/ip/ip_1/sim/bd_a15e_psr_aclk_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvlog -work smartconnect_v1_0 $xmvlog_opts -sv +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/f0b6/hdl/verilog" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/35de/hdl/verilog" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/ec67/hdl" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/c2c6" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/e2ba/hdl/verilog" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/a29c/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/f0b6/hdl/sc_util_v1_0_vl_rfs.sv" \
  "../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/bd53/hdl/sc_switchboard_v1_0_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts -sv +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/f0b6/hdl/verilog" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/35de/hdl/verilog" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/ec67/hdl" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/c2c6" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/e2ba/hdl/verilog" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/a29c/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../bd/rfdc_ex/ip/rfdc_ex_smartconnect_0_0/bd_0/ip/ip_2/sim/bd_a15e_arinsw_0.sv" \
  "../../../bd/rfdc_ex/ip/rfdc_ex_smartconnect_0_0/bd_0/ip/ip_3/sim/bd_a15e_rinsw_0.sv" \
  "../../../bd/rfdc_ex/ip/rfdc_ex_smartconnect_0_0/bd_0/ip/ip_4/sim/bd_a15e_awinsw_0.sv" \
  "../../../bd/rfdc_ex/ip/rfdc_ex_smartconnect_0_0/bd_0/ip/ip_5/sim/bd_a15e_winsw_0.sv" \
  "../../../bd/rfdc_ex/ip/rfdc_ex_smartconnect_0_0/bd_0/ip/ip_6/sim/bd_a15e_binsw_0.sv" \
  "../../../bd/rfdc_ex/ip/rfdc_ex_smartconnect_0_0/bd_0/ip/ip_7/sim/bd_a15e_aroutsw_0.sv" \
  "../../../bd/rfdc_ex/ip/rfdc_ex_smartconnect_0_0/bd_0/ip/ip_8/sim/bd_a15e_routsw_0.sv" \
  "../../../bd/rfdc_ex/ip/rfdc_ex_smartconnect_0_0/bd_0/ip/ip_9/sim/bd_a15e_awoutsw_0.sv" \
  "../../../bd/rfdc_ex/ip/rfdc_ex_smartconnect_0_0/bd_0/ip/ip_10/sim/bd_a15e_woutsw_0.sv" \
  "../../../bd/rfdc_ex/ip/rfdc_ex_smartconnect_0_0/bd_0/ip/ip_11/sim/bd_a15e_boutsw_0.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work smartconnect_v1_0 $xmvlog_opts -sv +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/f0b6/hdl/verilog" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/35de/hdl/verilog" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/ec67/hdl" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/c2c6" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/e2ba/hdl/verilog" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/a29c/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/35de/hdl/sc_node_v1_0_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts -sv +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/f0b6/hdl/verilog" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/35de/hdl/verilog" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/ec67/hdl" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/c2c6" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/e2ba/hdl/verilog" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/a29c/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../bd/rfdc_ex/ip/rfdc_ex_smartconnect_0_0/bd_0/ip/ip_12/sim/bd_a15e_arni_0.sv" \
  "../../../bd/rfdc_ex/ip/rfdc_ex_smartconnect_0_0/bd_0/ip/ip_13/sim/bd_a15e_rni_0.sv" \
  "../../../bd/rfdc_ex/ip/rfdc_ex_smartconnect_0_0/bd_0/ip/ip_14/sim/bd_a15e_awni_0.sv" \
  "../../../bd/rfdc_ex/ip/rfdc_ex_smartconnect_0_0/bd_0/ip/ip_15/sim/bd_a15e_wni_0.sv" \
  "../../../bd/rfdc_ex/ip/rfdc_ex_smartconnect_0_0/bd_0/ip/ip_16/sim/bd_a15e_bni_0.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work smartconnect_v1_0 $xmvlog_opts -sv +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/f0b6/hdl/verilog" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/35de/hdl/verilog" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/ec67/hdl" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/c2c6" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/e2ba/hdl/verilog" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/a29c/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/c6b2/hdl/sc_mmu_v1_0_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts -sv +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/f0b6/hdl/verilog" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/35de/hdl/verilog" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/ec67/hdl" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/c2c6" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/e2ba/hdl/verilog" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/a29c/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../bd/rfdc_ex/ip/rfdc_ex_smartconnect_0_0/bd_0/ip/ip_17/sim/bd_a15e_s00mmu_0.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work smartconnect_v1_0 $xmvlog_opts -sv +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/f0b6/hdl/verilog" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/35de/hdl/verilog" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/ec67/hdl" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/c2c6" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/e2ba/hdl/verilog" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/a29c/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/abb8/hdl/sc_transaction_regulator_v1_0_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts -sv +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/f0b6/hdl/verilog" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/35de/hdl/verilog" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/ec67/hdl" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/c2c6" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/e2ba/hdl/verilog" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/a29c/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../bd/rfdc_ex/ip/rfdc_ex_smartconnect_0_0/bd_0/ip/ip_18/sim/bd_a15e_s00tr_0.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work smartconnect_v1_0 $xmvlog_opts -sv +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/f0b6/hdl/verilog" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/35de/hdl/verilog" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/ec67/hdl" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/c2c6" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/e2ba/hdl/verilog" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/a29c/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/7827/hdl/sc_si_converter_v1_0_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts -sv +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/f0b6/hdl/verilog" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/35de/hdl/verilog" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/ec67/hdl" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/c2c6" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/e2ba/hdl/verilog" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/a29c/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../bd/rfdc_ex/ip/rfdc_ex_smartconnect_0_0/bd_0/ip/ip_19/sim/bd_a15e_s00sic_0.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work smartconnect_v1_0 $xmvlog_opts -sv +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/f0b6/hdl/verilog" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/35de/hdl/verilog" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/ec67/hdl" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/c2c6" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/e2ba/hdl/verilog" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/a29c/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/79ce/hdl/sc_axi2sc_v1_0_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts -sv +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/f0b6/hdl/verilog" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/35de/hdl/verilog" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/ec67/hdl" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/c2c6" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/e2ba/hdl/verilog" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/a29c/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../bd/rfdc_ex/ip/rfdc_ex_smartconnect_0_0/bd_0/ip/ip_20/sim/bd_a15e_s00a2s_0.sv" \
  "../../../bd/rfdc_ex/ip/rfdc_ex_smartconnect_0_0/bd_0/ip/ip_21/sim/bd_a15e_sarn_0.sv" \
  "../../../bd/rfdc_ex/ip/rfdc_ex_smartconnect_0_0/bd_0/ip/ip_22/sim/bd_a15e_srn_0.sv" \
  "../../../bd/rfdc_ex/ip/rfdc_ex_smartconnect_0_0/bd_0/ip/ip_23/sim/bd_a15e_sawn_0.sv" \
  "../../../bd/rfdc_ex/ip/rfdc_ex_smartconnect_0_0/bd_0/ip/ip_24/sim/bd_a15e_swn_0.sv" \
  "../../../bd/rfdc_ex/ip/rfdc_ex_smartconnect_0_0/bd_0/ip/ip_25/sim/bd_a15e_sbn_0.sv" \
  "../../../bd/rfdc_ex/ip/rfdc_ex_smartconnect_0_0/bd_0/ip/ip_26/sim/bd_a15e_s01mmu_0.sv" \
  "../../../bd/rfdc_ex/ip/rfdc_ex_smartconnect_0_0/bd_0/ip/ip_27/sim/bd_a15e_s01tr_0.sv" \
  "../../../bd/rfdc_ex/ip/rfdc_ex_smartconnect_0_0/bd_0/ip/ip_28/sim/bd_a15e_s01sic_0.sv" \
  "../../../bd/rfdc_ex/ip/rfdc_ex_smartconnect_0_0/bd_0/ip/ip_29/sim/bd_a15e_s01a2s_0.sv" \
  "../../../bd/rfdc_ex/ip/rfdc_ex_smartconnect_0_0/bd_0/ip/ip_30/sim/bd_a15e_sarn_1.sv" \
  "../../../bd/rfdc_ex/ip/rfdc_ex_smartconnect_0_0/bd_0/ip/ip_31/sim/bd_a15e_srn_1.sv" \
  "../../../bd/rfdc_ex/ip/rfdc_ex_smartconnect_0_0/bd_0/ip/ip_32/sim/bd_a15e_sawn_1.sv" \
  "../../../bd/rfdc_ex/ip/rfdc_ex_smartconnect_0_0/bd_0/ip/ip_33/sim/bd_a15e_swn_1.sv" \
  "../../../bd/rfdc_ex/ip/rfdc_ex_smartconnect_0_0/bd_0/ip/ip_34/sim/bd_a15e_sbn_1.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work smartconnect_v1_0 $xmvlog_opts -sv +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/f0b6/hdl/verilog" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/35de/hdl/verilog" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/ec67/hdl" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/c2c6" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/e2ba/hdl/verilog" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/a29c/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/ebf7/hdl/sc_sc2axi_v1_0_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts -sv +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/f0b6/hdl/verilog" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/35de/hdl/verilog" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/ec67/hdl" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/c2c6" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/e2ba/hdl/verilog" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/a29c/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../bd/rfdc_ex/ip/rfdc_ex_smartconnect_0_0/bd_0/ip/ip_35/sim/bd_a15e_m00s2a_0.sv" \
  "../../../bd/rfdc_ex/ip/rfdc_ex_smartconnect_0_0/bd_0/ip/ip_36/sim/bd_a15e_m00arn_0.sv" \
  "../../../bd/rfdc_ex/ip/rfdc_ex_smartconnect_0_0/bd_0/ip/ip_37/sim/bd_a15e_m00rn_0.sv" \
  "../../../bd/rfdc_ex/ip/rfdc_ex_smartconnect_0_0/bd_0/ip/ip_38/sim/bd_a15e_m00awn_0.sv" \
  "../../../bd/rfdc_ex/ip/rfdc_ex_smartconnect_0_0/bd_0/ip/ip_39/sim/bd_a15e_m00wn_0.sv" \
  "../../../bd/rfdc_ex/ip/rfdc_ex_smartconnect_0_0/bd_0/ip/ip_40/sim/bd_a15e_m00bn_0.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work smartconnect_v1_0 $xmvlog_opts -sv +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/f0b6/hdl/verilog" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/35de/hdl/verilog" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/ec67/hdl" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/c2c6" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/e2ba/hdl/verilog" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/a29c/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/6eea/hdl/sc_exit_v1_0_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts -sv +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/f0b6/hdl/verilog" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/35de/hdl/verilog" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/ec67/hdl" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/c2c6" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/e2ba/hdl/verilog" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/a29c/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../bd/rfdc_ex/ip/rfdc_ex_smartconnect_0_0/bd_0/ip/ip_41/sim/bd_a15e_m00e_0.sv" \
  "../../../bd/rfdc_ex/ip/rfdc_ex_smartconnect_0_0/bd_0/ip/ip_42/sim/bd_a15e_m01s2a_0.sv" \
  "../../../bd/rfdc_ex/ip/rfdc_ex_smartconnect_0_0/bd_0/ip/ip_43/sim/bd_a15e_m01arn_0.sv" \
  "../../../bd/rfdc_ex/ip/rfdc_ex_smartconnect_0_0/bd_0/ip/ip_44/sim/bd_a15e_m01rn_0.sv" \
  "../../../bd/rfdc_ex/ip/rfdc_ex_smartconnect_0_0/bd_0/ip/ip_45/sim/bd_a15e_m01awn_0.sv" \
  "../../../bd/rfdc_ex/ip/rfdc_ex_smartconnect_0_0/bd_0/ip/ip_46/sim/bd_a15e_m01wn_0.sv" \
  "../../../bd/rfdc_ex/ip/rfdc_ex_smartconnect_0_0/bd_0/ip/ip_47/sim/bd_a15e_m01bn_0.sv" \
  "../../../bd/rfdc_ex/ip/rfdc_ex_smartconnect_0_0/bd_0/ip/ip_48/sim/bd_a15e_m01e_0.sv" \
  "../../../bd/rfdc_ex/ip/rfdc_ex_smartconnect_0_0/bd_0/ip/ip_49/sim/bd_a15e_m02s2a_0.sv" \
  "../../../bd/rfdc_ex/ip/rfdc_ex_smartconnect_0_0/bd_0/ip/ip_50/sim/bd_a15e_m02arn_0.sv" \
  "../../../bd/rfdc_ex/ip/rfdc_ex_smartconnect_0_0/bd_0/ip/ip_51/sim/bd_a15e_m02rn_0.sv" \
  "../../../bd/rfdc_ex/ip/rfdc_ex_smartconnect_0_0/bd_0/ip/ip_52/sim/bd_a15e_m02awn_0.sv" \
  "../../../bd/rfdc_ex/ip/rfdc_ex_smartconnect_0_0/bd_0/ip/ip_53/sim/bd_a15e_m02wn_0.sv" \
  "../../../bd/rfdc_ex/ip/rfdc_ex_smartconnect_0_0/bd_0/ip/ip_54/sim/bd_a15e_m02bn_0.sv" \
  "../../../bd/rfdc_ex/ip/rfdc_ex_smartconnect_0_0/bd_0/ip/ip_55/sim/bd_a15e_m02e_0.sv" \
  "../../../bd/rfdc_ex/ip/rfdc_ex_smartconnect_0_0/bd_0/ip/ip_56/sim/bd_a15e_m03s2a_0.sv" \
  "../../../bd/rfdc_ex/ip/rfdc_ex_smartconnect_0_0/bd_0/ip/ip_57/sim/bd_a15e_m03arn_0.sv" \
  "../../../bd/rfdc_ex/ip/rfdc_ex_smartconnect_0_0/bd_0/ip/ip_58/sim/bd_a15e_m03rn_0.sv" \
  "../../../bd/rfdc_ex/ip/rfdc_ex_smartconnect_0_0/bd_0/ip/ip_59/sim/bd_a15e_m03awn_0.sv" \
  "../../../bd/rfdc_ex/ip/rfdc_ex_smartconnect_0_0/bd_0/ip/ip_60/sim/bd_a15e_m03wn_0.sv" \
  "../../../bd/rfdc_ex/ip/rfdc_ex_smartconnect_0_0/bd_0/ip/ip_61/sim/bd_a15e_m03bn_0.sv" \
  "../../../bd/rfdc_ex/ip/rfdc_ex_smartconnect_0_0/bd_0/ip/ip_62/sim/bd_a15e_m03e_0.sv" \
  "../../../bd/rfdc_ex/ip/rfdc_ex_smartconnect_0_0/bd_0/ip/ip_63/sim/bd_a15e_m04s2a_0.sv" \
  "../../../bd/rfdc_ex/ip/rfdc_ex_smartconnect_0_0/bd_0/ip/ip_64/sim/bd_a15e_m04arn_0.sv" \
  "../../../bd/rfdc_ex/ip/rfdc_ex_smartconnect_0_0/bd_0/ip/ip_65/sim/bd_a15e_m04rn_0.sv" \
  "../../../bd/rfdc_ex/ip/rfdc_ex_smartconnect_0_0/bd_0/ip/ip_66/sim/bd_a15e_m04awn_0.sv" \
  "../../../bd/rfdc_ex/ip/rfdc_ex_smartconnect_0_0/bd_0/ip/ip_67/sim/bd_a15e_m04wn_0.sv" \
  "../../../bd/rfdc_ex/ip/rfdc_ex_smartconnect_0_0/bd_0/ip/ip_68/sim/bd_a15e_m04bn_0.sv" \
  "../../../bd/rfdc_ex/ip/rfdc_ex_smartconnect_0_0/bd_0/ip/ip_69/sim/bd_a15e_m04e_0.sv" \
  "../../../bd/rfdc_ex/ip/rfdc_ex_smartconnect_0_0/bd_0/ip/ip_70/sim/bd_a15e_m05s2a_0.sv" \
  "../../../bd/rfdc_ex/ip/rfdc_ex_smartconnect_0_0/bd_0/ip/ip_71/sim/bd_a15e_m05arn_0.sv" \
  "../../../bd/rfdc_ex/ip/rfdc_ex_smartconnect_0_0/bd_0/ip/ip_72/sim/bd_a15e_m05rn_0.sv" \
  "../../../bd/rfdc_ex/ip/rfdc_ex_smartconnect_0_0/bd_0/ip/ip_73/sim/bd_a15e_m05awn_0.sv" \
  "../../../bd/rfdc_ex/ip/rfdc_ex_smartconnect_0_0/bd_0/ip/ip_74/sim/bd_a15e_m05wn_0.sv" \
  "../../../bd/rfdc_ex/ip/rfdc_ex_smartconnect_0_0/bd_0/ip/ip_75/sim/bd_a15e_m05bn_0.sv" \
  "../../../bd/rfdc_ex/ip/rfdc_ex_smartconnect_0_0/bd_0/ip/ip_76/sim/bd_a15e_m05e_0.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work axi_infrastructure_v1_1_0 $xmvlog_opts +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/f0b6/hdl/verilog" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/35de/hdl/verilog" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/ec67/hdl" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/c2c6" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/e2ba/hdl/verilog" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/a29c/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work axi_register_slice_v2_1_29 $xmvlog_opts +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/f0b6/hdl/verilog" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/35de/hdl/verilog" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/ec67/hdl" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/c2c6" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/e2ba/hdl/verilog" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/a29c/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/ff9f/hdl/axi_register_slice_v2_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work axi_vip_v1_1_15 $xmvlog_opts -sv +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/f0b6/hdl/verilog" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/35de/hdl/verilog" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/ec67/hdl" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/c2c6" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/e2ba/hdl/verilog" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/a29c/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/5753/hdl/axi_vip_v1_1_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/f0b6/hdl/verilog" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/35de/hdl/verilog" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/ec67/hdl" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/c2c6" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/e2ba/hdl/verilog" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/a29c/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../bd/rfdc_ex/ip/rfdc_ex_smartconnect_0_0/sim/rfdc_ex_smartconnect_0_0.v" \
  "../../../bd/rfdc_ex/ip/rfdc_ex_adc_sink_i_0/sim/rfdc_ex_adc_sink_i_0.v" \
  "../../../bd/rfdc_ex/ip/rfdc_ex_dac_source_i_0/sim/rfdc_ex_dac_source_i_0.v" \
  "../../../bd/rfdc_ex/ip/rfdc_ex_usp_rf_data_converter_0_0/synth/rfdc_ex_usp_rf_data_converter_0_0_block.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts -sv +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/f0b6/hdl/verilog" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/35de/hdl/verilog" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/ec67/hdl" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/c2c6" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/e2ba/hdl/verilog" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/a29c/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../bd/rfdc_ex/ip/rfdc_ex_usp_rf_data_converter_0_0/synth/rfdc_ex_usp_rf_data_converter_0_0_por_fsm_top.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/f0b6/hdl/verilog" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/35de/hdl/verilog" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/ec67/hdl" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/c2c6" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/e2ba/hdl/verilog" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/a29c/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../bd/rfdc_ex/ip/rfdc_ex_usp_rf_data_converter_0_0/synth/rfdc_ex_usp_rf_data_converter_0_0_bgt_fsm.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts -sv +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/f0b6/hdl/verilog" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/35de/hdl/verilog" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/ec67/hdl" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/c2c6" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/e2ba/hdl/verilog" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/a29c/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../bd/rfdc_ex/ip/rfdc_ex_usp_rf_data_converter_0_0/synth/rfdc_ex_usp_rf_data_converter_0_0_device_rom.sv" \
  "../../../bd/rfdc_ex/ip/rfdc_ex_usp_rf_data_converter_0_0/synth/rfdc_ex_usp_rf_data_converter_0_0_por_fsm.sv" \
  "../../../bd/rfdc_ex/ip/rfdc_ex_usp_rf_data_converter_0_0/synth/rfdc_ex_usp_rf_data_converter_0_0_por_fsm_disabled.sv" \
  "../../../bd/rfdc_ex/ip/rfdc_ex_usp_rf_data_converter_0_0/synth/rfdc_ex_usp_rf_data_converter_0_0_tile_config.sv" \
  "../../../bd/rfdc_ex/ip/rfdc_ex_usp_rf_data_converter_0_0/synth/rfdc_ex_usp_rf_data_converter_0_0_constants_config.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/f0b6/hdl/verilog" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/35de/hdl/verilog" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/ec67/hdl" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/c2c6" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/e2ba/hdl/verilog" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/a29c/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../bd/rfdc_ex/ip/rfdc_ex_usp_rf_data_converter_0_0/synth/rfdc_ex_usp_rf_data_converter_0_0_drp_arbiter.v" \
  "../../../bd/rfdc_ex/ip/rfdc_ex_usp_rf_data_converter_0_0/synth/rfdc_ex_usp_rf_data_converter_0_0_drp_arbiter_adc.v" \
  "../../../bd/rfdc_ex/ip/rfdc_ex_usp_rf_data_converter_0_0/synth/rfdc_ex_usp_rf_data_converter_0_0_register_decode.v" \
  "../../../bd/rfdc_ex/ip/rfdc_ex_usp_rf_data_converter_0_0/synth/rfdc_ex_usp_rf_data_converter_0_0_address_decoder.v" \
  "../../../bd/rfdc_ex/ip/rfdc_ex_usp_rf_data_converter_0_0/synth/rfdc_ex_usp_rf_data_converter_0_0_axi_lite_ipif.v" \
  "../../../bd/rfdc_ex/ip/rfdc_ex_usp_rf_data_converter_0_0/synth/rfdc_ex_usp_rf_data_converter_0_0_counter_f.v" \
  "../../../bd/rfdc_ex/ip/rfdc_ex_usp_rf_data_converter_0_0/synth/rfdc_ex_usp_rf_data_converter_0_0_pselect_f.v" \
  "../../../bd/rfdc_ex/ip/rfdc_ex_usp_rf_data_converter_0_0/synth/rfdc_ex_usp_rf_data_converter_0_0_slave_attachment.v" \
  "../../../bd/rfdc_ex/ip/rfdc_ex_usp_rf_data_converter_0_0/synth/rfdc_ex_usp_rf_data_converter_0_0_rf_wrapper.v" \
  "../../../bd/rfdc_ex/ip/rfdc_ex_usp_rf_data_converter_0_0/synth/rfdc_ex_usp_rf_data_converter_0_0_drp_control_top.v" \
  "../../../bd/rfdc_ex/ip/rfdc_ex_usp_rf_data_converter_0_0/synth/rfdc_ex_usp_rf_data_converter_0_0_drp_control.v" \
  "../../../bd/rfdc_ex/ip/rfdc_ex_usp_rf_data_converter_0_0/synth/rfdc_ex_usp_rf_data_converter_0_0_drp_access_ctrl.v" \
  "../../../bd/rfdc_ex/ip/rfdc_ex_usp_rf_data_converter_0_0/synth/rfdc_ex_usp_rf_data_converter_0_0_irq_req_ack.v" \
  "../../../bd/rfdc_ex/ip/rfdc_ex_usp_rf_data_converter_0_0/synth/rfdc_ex_usp_rf_data_converter_0_0_irq_sync.v" \
  "../../../bd/rfdc_ex/ip/rfdc_ex_usp_rf_data_converter_0_0/synth/rfdc_ex_usp_rf_data_converter_0_0bufg_gt_ctrl.v" \
  "../../../bd/rfdc_ex/ip/rfdc_ex_usp_rf_data_converter_0_0/synth/rfdc_ex_usp_rf_data_converter_0_0_overvol_irq.v" \
  "../../../bd/rfdc_ex/ip/rfdc_ex_usp_rf_data_converter_0_0/synth/rfdc_ex_usp_rf_data_converter_0_0_powerup_state_irq.v" \
  "../../../bd/rfdc_ex/ip/rfdc_ex_usp_rf_data_converter_0_0/synth/rfdc_ex_usp_rf_data_converter_0_0_rst_cnt.v" \
  "../../../bd/rfdc_ex/ip/rfdc_ex_usp_rf_data_converter_0_0/synth/rfdc_ex_usp_rf_data_converter_0_0_clk_detection.v" \
  "../../../bd/rfdc_ex/ip/rfdc_ex_usp_rf_data_converter_0_0/synth/rfdc_ex_usp_rf_data_converter_0_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work jtag_axi $xmvlog_opts +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/f0b6/hdl/verilog" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/35de/hdl/verilog" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/ec67/hdl" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/c2c6" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/e2ba/hdl/verilog" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/a29c/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/b140/hdl/jtag_axi_v1_2_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/f0b6/hdl/verilog" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/35de/hdl/verilog" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/ec67/hdl" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/c2c6" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/e2ba/hdl/verilog" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/a29c/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../bd/rfdc_ex/ip/rfdc_ex_jtag_axi_0_0/sim/rfdc_ex_jtag_axi_0_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work microblaze_v11_0_12 $xmvhdl_opts \
  "../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/f557/hdl/microblaze_v11_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work xil_defaultlib $xmvhdl_opts \
  "../../../bd/rfdc_ex/ip/rfdc_ex_microblaze_0_0/sim/rfdc_ex_microblaze_0_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work axi_lite_ipif_v3_0_4 $xmvhdl_opts \
  "../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/66ea/hdl/axi_lite_ipif_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work mdm_v3_2_25 $xmvhdl_opts \
  "../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/347d/hdl/mdm_v3_2_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work xil_defaultlib $xmvhdl_opts \
  "../../../bd/rfdc_ex/ip/rfdc_ex_mdm_1_0/sim/rfdc_ex_mdm_1_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work lmb_bram_if_cntlr_v4_0_23 $xmvhdl_opts \
  "../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/1ca4/hdl/lmb_bram_if_cntlr_v4_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work xil_defaultlib $xmvhdl_opts \
  "../../../bd/rfdc_ex/ip/rfdc_ex_dlmb_bram_if_cntlr_0/sim/rfdc_ex_dlmb_bram_if_cntlr_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work lmb_v10_v3_0_13 $xmvhdl_opts \
  "../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/ae24/hdl/lmb_v10_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work xil_defaultlib $xmvhdl_opts \
  "../../../bd/rfdc_ex/ip/rfdc_ex_dlmb_v10_0/sim/rfdc_ex_dlmb_v10_0.vhd" \
  "../../../bd/rfdc_ex/ip/rfdc_ex_ilmb_bram_if_cntlr_0/sim/rfdc_ex_ilmb_bram_if_cntlr_0.vhd" \
  "../../../bd/rfdc_ex/ip/rfdc_ex_ilmb_v10_0/sim/rfdc_ex_ilmb_v10_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvlog -work blk_mem_gen_v8_4_7 $xmvlog_opts +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/f0b6/hdl/verilog" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/35de/hdl/verilog" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/ec67/hdl" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/c2c6" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/e2ba/hdl/verilog" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/a29c/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/3c0c/simulation/blk_mem_gen_v8_4.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/f0b6/hdl/verilog" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/35de/hdl/verilog" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/ec67/hdl" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/c2c6" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/e2ba/hdl/verilog" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/a29c/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../bd/rfdc_ex/ip/rfdc_ex_lmb_bram_0/sim/rfdc_ex_lmb_bram_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work xil_defaultlib $xmvhdl_opts \
  "../../../bd/rfdc_ex/ip/rfdc_ex_rst_s_axi_aclk_57M_0/sim/rfdc_ex_rst_s_axi_aclk_57M_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/f0b6/hdl/verilog" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/35de/hdl/verilog" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/ec67/hdl" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/c2c6" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/e2ba/hdl/verilog" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/a29c/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../bd/rfdc_ex/ip/rfdc_ex_clk_wiz_dac0_0/rfdc_ex_clk_wiz_dac0_0_mmcm_pll_drp.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work xil_defaultlib $xmvhdl_opts \
  "../../../bd/rfdc_ex/ip/rfdc_ex_clk_wiz_dac0_0/proc_common_v3_00_a/hdl/src/vhdl/rfdc_ex_clk_wiz_dac0_0_conv_funs_pkg.vhd" \
  "../../../bd/rfdc_ex/ip/rfdc_ex_clk_wiz_dac0_0/proc_common_v3_00_a/hdl/src/vhdl/rfdc_ex_clk_wiz_dac0_0_proc_common_pkg.vhd" \
  "../../../bd/rfdc_ex/ip/rfdc_ex_clk_wiz_dac0_0/proc_common_v3_00_a/hdl/src/vhdl/rfdc_ex_clk_wiz_dac0_0_ipif_pkg.vhd" \
  "../../../bd/rfdc_ex/ip/rfdc_ex_clk_wiz_dac0_0/proc_common_v3_00_a/hdl/src/vhdl/rfdc_ex_clk_wiz_dac0_0_family_support.vhd" \
  "../../../bd/rfdc_ex/ip/rfdc_ex_clk_wiz_dac0_0/proc_common_v3_00_a/hdl/src/vhdl/rfdc_ex_clk_wiz_dac0_0_family.vhd" \
  "../../../bd/rfdc_ex/ip/rfdc_ex_clk_wiz_dac0_0/proc_common_v3_00_a/hdl/src/vhdl/rfdc_ex_clk_wiz_dac0_0_soft_reset.vhd" \
  "../../../bd/rfdc_ex/ip/rfdc_ex_clk_wiz_dac0_0/proc_common_v3_00_a/hdl/src/vhdl/rfdc_ex_clk_wiz_dac0_0_pselect_f.vhd" \
  "../../../bd/rfdc_ex/ip/rfdc_ex_clk_wiz_dac0_0/axi_lite_ipif_v1_01_a/hdl/src/vhdl/rfdc_ex_clk_wiz_dac0_0_address_decoder.vhd" \
  "../../../bd/rfdc_ex/ip/rfdc_ex_clk_wiz_dac0_0/axi_lite_ipif_v1_01_a/hdl/src/vhdl/rfdc_ex_clk_wiz_dac0_0_slave_attachment.vhd" \
  "../../../bd/rfdc_ex/ip/rfdc_ex_clk_wiz_dac0_0/axi_lite_ipif_v1_01_a/hdl/src/vhdl/rfdc_ex_clk_wiz_dac0_0_axi_lite_ipif.vhd" \
  "../../../bd/rfdc_ex/ip/rfdc_ex_clk_wiz_dac0_0/rfdc_ex_clk_wiz_dac0_0_clk_wiz_drp.vhd" \
  "../../../bd/rfdc_ex/ip/rfdc_ex_clk_wiz_dac0_0/rfdc_ex_clk_wiz_dac0_0_axi_clk_config.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/f0b6/hdl/verilog" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/35de/hdl/verilog" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/ec67/hdl" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/c2c6" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/e2ba/hdl/verilog" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/a29c/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../bd/rfdc_ex/ip/rfdc_ex_clk_wiz_dac0_0/rfdc_ex_clk_wiz_dac0_0_clk_wiz.v" \
  "../../../bd/rfdc_ex/ip/rfdc_ex_clk_wiz_dac0_0/rfdc_ex_clk_wiz_dac0_0.v" \
  "../../../bd/rfdc_ex/ip/rfdc_ex_clk_wiz_adc0_0/rfdc_ex_clk_wiz_adc0_0_mmcm_pll_drp.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work xil_defaultlib $xmvhdl_opts \
  "../../../bd/rfdc_ex/ip/rfdc_ex_clk_wiz_adc0_0/proc_common_v3_00_a/hdl/src/vhdl/rfdc_ex_clk_wiz_adc0_0_conv_funs_pkg.vhd" \
  "../../../bd/rfdc_ex/ip/rfdc_ex_clk_wiz_adc0_0/proc_common_v3_00_a/hdl/src/vhdl/rfdc_ex_clk_wiz_adc0_0_proc_common_pkg.vhd" \
  "../../../bd/rfdc_ex/ip/rfdc_ex_clk_wiz_adc0_0/proc_common_v3_00_a/hdl/src/vhdl/rfdc_ex_clk_wiz_adc0_0_ipif_pkg.vhd" \
  "../../../bd/rfdc_ex/ip/rfdc_ex_clk_wiz_adc0_0/proc_common_v3_00_a/hdl/src/vhdl/rfdc_ex_clk_wiz_adc0_0_family_support.vhd" \
  "../../../bd/rfdc_ex/ip/rfdc_ex_clk_wiz_adc0_0/proc_common_v3_00_a/hdl/src/vhdl/rfdc_ex_clk_wiz_adc0_0_family.vhd" \
  "../../../bd/rfdc_ex/ip/rfdc_ex_clk_wiz_adc0_0/proc_common_v3_00_a/hdl/src/vhdl/rfdc_ex_clk_wiz_adc0_0_soft_reset.vhd" \
  "../../../bd/rfdc_ex/ip/rfdc_ex_clk_wiz_adc0_0/proc_common_v3_00_a/hdl/src/vhdl/rfdc_ex_clk_wiz_adc0_0_pselect_f.vhd" \
  "../../../bd/rfdc_ex/ip/rfdc_ex_clk_wiz_adc0_0/axi_lite_ipif_v1_01_a/hdl/src/vhdl/rfdc_ex_clk_wiz_adc0_0_address_decoder.vhd" \
  "../../../bd/rfdc_ex/ip/rfdc_ex_clk_wiz_adc0_0/axi_lite_ipif_v1_01_a/hdl/src/vhdl/rfdc_ex_clk_wiz_adc0_0_slave_attachment.vhd" \
  "../../../bd/rfdc_ex/ip/rfdc_ex_clk_wiz_adc0_0/axi_lite_ipif_v1_01_a/hdl/src/vhdl/rfdc_ex_clk_wiz_adc0_0_axi_lite_ipif.vhd" \
  "../../../bd/rfdc_ex/ip/rfdc_ex_clk_wiz_adc0_0/rfdc_ex_clk_wiz_adc0_0_clk_wiz_drp.vhd" \
  "../../../bd/rfdc_ex/ip/rfdc_ex_clk_wiz_adc0_0/rfdc_ex_clk_wiz_adc0_0_axi_clk_config.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/f0b6/hdl/verilog" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/35de/hdl/verilog" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/ec67/hdl" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/c2c6" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/e2ba/hdl/verilog" +incdir+"../../../../usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ipshared/a29c/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../bd/rfdc_ex/ip/rfdc_ex_clk_wiz_adc0_0/rfdc_ex_clk_wiz_adc0_0_clk_wiz.v" \
  "../../../bd/rfdc_ex/ip/rfdc_ex_clk_wiz_adc0_0/rfdc_ex_clk_wiz_adc0_0.v" \
  "../../../bd/rfdc_ex/sim/rfdc_ex.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts \
  glbl.v \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null
}

# RUN_STEP: <elaborate>
elaborate()
{
  xmelab $xmelab_opts $design_libs_elab xil_defaultlib.rfdc_ex xil_defaultlib.glbl
}

# RUN_STEP: <simulate>
simulate()
{
  xmsim $xmsim_opts xil_defaultlib.rfdc_ex -input simulate.do
}

# STEP: setup
setup()
{
  # delete previous files for a clean rerun
  if [[ ($b_reset_run == 1) ]]; then
    reset_run
    echo -e "INFO: Simulation run files deleted.\n"
    exit 0
  fi

 # delete previous log files
  if [[ ($b_reset_log == 1) ]]; then
    reset_log
    echo -e "INFO: Simulation run log files deleted.\n"
    exit 0
  fi

  # add any setup/initialization commands here:-

  # <user specific commands>

}

# simulator index file/library directory processing
init_lib()
{
  if [[ ($b_keep_index == 1) ]]; then
    # keep previous design library mappings
    true
  else
    # define design library mappings
    create_lib_mappings
  fi

  if [[ ($b_keep_index == 1) ]]; then
    # do not recreate design library directories
    true
  else
    # create design library directories
    create_lib_dir
  fi
}

# define design library mappings
create_lib_mappings()
{
  file="hdl.var"
  touch $file

  file="cds.lib"
  if [[ -e $file ]]; then
    if [[ ($lib_map_path == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file


  if [[ ($lib_map_path != "") ]]; then
    incl_ref="INCLUDE $lib_map_path/cds.lib"
    echo $incl_ref >> $file
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="DEFINE $lib $sim_lib_dir/$lib"
    echo $mapping >> $file
  done
}

# create design library directory
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi
  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# delete generated data from the previous run
reset_run()
{
  files_to_remove=(xmvlog.log xmvhdl.log xmsc.log compile.log elaborate.log simulate.log diag_report.log xsc_report.log rfdc_ex_sc.so .tmp_log xcelium_lib waves.shm c.obj)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done
}

# delete generated log files from the previous run
reset_log()
{
  files_to_remove=(xmvlog.log xmvhdl.log xmsc.log compile.log elaborate.log simulate.log diag_report.log xsc_report.log .tmp_log)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done
}

# check switch argument value
check_arg_value()
{
  if [[ ($1 == "-step") && (($2 != "compile") && ($2 != "elaborate") && ($2 != "simulate")) ]];then
    echo -e "ERROR: Invalid or missing step '$2' (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($1 == "-lib_map_path") && ($2 == "") ]];then
    echo -e "ERROR: Simulation library directory path not specified (type \"./rfdc_ex.sh -help\" for more information)\n"
    exit 1
  fi
}

# check command line arguments
check_args()
{
  arg_count=$#
  if [[ ("$#" == 1) && (("$1" == "-help") || ("$1" == "-h")) ]]; then
    usage
  fi
  while [[ "$#" -gt 0 ]]; do
    case $1 in
      -step)          check_arg_value $1 $2;step=$2;         b_step=1;         shift;;
      -lib_map_path)  check_arg_value $1 $2;lib_map_path=$2; b_lib_map_path=1; shift;;
      -gen_bypass)    b_gen_bypass=1    ;;
      -reset_run)     b_reset_run=1     ;;
      -reset_log)     b_reset_log=1     ;;
      -keep_index)    b_keep_index=1    ;;
      -noclean_files) b_noclean_files=1 ;;
      -help|-h)       ;;
      *) echo -e "ERROR: Invalid option specified '$1' (type "./top.sh -help" for more information)\n"; exit 1 ;;
    esac
     shift
  done

  # -reset_run is not applicable with other switches
  if [[ ("$arg_count" -gt 1) && ($b_reset_run == 1) ]]; then
    echo -e "ERROR: -reset_run switch is not applicable with other switches (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi

  # -reset_log is not applicable with other switches
  if [[ ("$arg_count" -gt 1) && ($b_reset_log == 1) ]]; then
    echo -e "ERROR: -reset_log switch is not applicable with other switches (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi

  # -keep_index is not applicable with other switches
  if [[ ("$arg_count" -gt 1) && ($b_keep_index == 1) ]]; then
    echo -e "ERROR: -keep_index switch is not applicable with other switches (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi

  # -noclean_files is not applicable with other switches
  if [[ ("$arg_count" -gt 1) && ($b_noclean_files == 1) ]]; then
    echo -e "ERROR: -noclean_files switch is not applicable with other switches (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi
}

# script usage
usage()
{
  msg="Usage: rfdc_ex.sh [-help]\n\
Usage: rfdc_ex.sh [-step]\n\
Usage: rfdc_ex.sh [-lib_map_path]\n\
Usage: rfdc_ex.sh [-reset_run]\n\
Usage: rfdc_ex.sh [-reset_log]\n\
Usage: rfdc_ex.sh [-keep_index]\n\
Usage: rfdc_ex.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-step <name>] -- Execute specified step (simulate)\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Delete simulator generated data files from the previous run and recreate simulator setup\n\
file/library mappings for a clean run. This switch will not execute steps defined in the script.\n\n\
NOTE: To keep simulator index file settings from the previous run, use the -keep_index switch\n\
NOTE: To regenerate simulator index file but keep the simulator generated files, use the -noclean_files switch\n\n\
[-reset_log] -- Delete simulator generated log files from the previous run\n\n\
[-keep_index] -- Keep simulator index file settings from the previous run\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run\n"
  echo -e $msg
  exit 0
}

# initialize globals
step=""
lib_map_path=""
b_step=0
b_lib_map_path=0
b_gen_bypass=0
b_reset_run=0
b_reset_log=0
b_keep_index=0
b_noclean_files=0

# launch script
run $*
