# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/tommy/RfSoc/usp_rf_data_converter_0_ex/usp_rf_data_converter_0_ex.srcs/sources_1/bd/rfdc_ex/ip/rfdc_ex_jtag_axi_0_0/rfdc_ex_jtag_axi_0_0.xci
# IP: The module: 'rfdc_ex_jtag_axi_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/tommy/RfSoc/usp_rf_data_converter_0_ex/usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ip/rfdc_ex_jtag_axi_0_0/constraints/jtag_axi.xdc
# XDC: The top module name and the constraint reference have the same name: 'rfdc_ex_jtag_axi_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/tommy/RfSoc/usp_rf_data_converter_0_ex/usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ip/rfdc_ex_jtag_axi_0_0/rfdc_ex_jtag_axi_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rfdc_ex_jtag_axi_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/tommy/RfSoc/usp_rf_data_converter_0_ex/usp_rf_data_converter_0_ex.srcs/sources_1/bd/rfdc_ex/ip/rfdc_ex_jtag_axi_0_0/rfdc_ex_jtag_axi_0_0.xci
# IP: The module: 'rfdc_ex_jtag_axi_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/tommy/RfSoc/usp_rf_data_converter_0_ex/usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ip/rfdc_ex_jtag_axi_0_0/constraints/jtag_axi.xdc
# XDC: The top module name and the constraint reference have the same name: 'rfdc_ex_jtag_axi_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/tommy/RfSoc/usp_rf_data_converter_0_ex/usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/ip/rfdc_ex_jtag_axi_0_0/rfdc_ex_jtag_axi_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rfdc_ex_jtag_axi_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
