# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: c:/Users/tommy/RfSoc/usp_rf_data_converter_0_ex/imports/usp_rf_data_converter_0_example_design.xdc

# Block Designs: bd/rfdc_ex/rfdc_ex.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rfdc_ex || ORIG_REF_NAME==rfdc_ex} -quiet] -quiet

# IP: bd/rfdc_ex/ip/rfdc_ex_smartconnect_0_0/rfdc_ex_smartconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rfdc_ex_smartconnect_0_0 || ORIG_REF_NAME==rfdc_ex_smartconnect_0_0} -quiet] -quiet

# IP: bd/rfdc_ex/ip/rfdc_ex_adc_sink_i_0/rfdc_ex_adc_sink_i_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rfdc_ex_adc_sink_i_0 || ORIG_REF_NAME==rfdc_ex_adc_sink_i_0} -quiet] -quiet

# IP: bd/rfdc_ex/ip/rfdc_ex_dac_source_i_0/rfdc_ex_dac_source_i_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rfdc_ex_dac_source_i_0 || ORIG_REF_NAME==rfdc_ex_dac_source_i_0} -quiet] -quiet

# IP: bd/rfdc_ex/ip/rfdc_ex_usp_rf_data_converter_0_0/rfdc_ex_usp_rf_data_converter_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rfdc_ex_usp_rf_data_converter_0_0 || ORIG_REF_NAME==rfdc_ex_usp_rf_data_converter_0_0} -quiet] -quiet

# IP: bd/rfdc_ex/ip/rfdc_ex_jtag_axi_0_0/rfdc_ex_jtag_axi_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rfdc_ex_jtag_axi_0_0 || ORIG_REF_NAME==rfdc_ex_jtag_axi_0_0} -quiet] -quiet

# IP: bd/rfdc_ex/ip/rfdc_ex_microblaze_0_0/rfdc_ex_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rfdc_ex_microblaze_0_0 || ORIG_REF_NAME==rfdc_ex_microblaze_0_0} -quiet] -quiet

# IP: bd/rfdc_ex/ip/rfdc_ex_mdm_1_0/rfdc_ex_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rfdc_ex_mdm_1_0 || ORIG_REF_NAME==rfdc_ex_mdm_1_0} -quiet] -quiet

# IP: bd/rfdc_ex/ip/rfdc_ex_dlmb_bram_if_cntlr_0/rfdc_ex_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rfdc_ex_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==rfdc_ex_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/rfdc_ex/ip/rfdc_ex_dlmb_v10_0/rfdc_ex_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rfdc_ex_dlmb_v10_0 || ORIG_REF_NAME==rfdc_ex_dlmb_v10_0} -quiet] -quiet

# IP: bd/rfdc_ex/ip/rfdc_ex_ilmb_bram_if_cntlr_0/rfdc_ex_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rfdc_ex_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==rfdc_ex_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/rfdc_ex/ip/rfdc_ex_ilmb_v10_0/rfdc_ex_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rfdc_ex_ilmb_v10_0 || ORIG_REF_NAME==rfdc_ex_ilmb_v10_0} -quiet] -quiet

# IP: bd/rfdc_ex/ip/rfdc_ex_lmb_bram_0/rfdc_ex_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rfdc_ex_lmb_bram_0 || ORIG_REF_NAME==rfdc_ex_lmb_bram_0} -quiet] -quiet

# IP: bd/rfdc_ex/ip/rfdc_ex_rst_s_axi_aclk_57M_0/rfdc_ex_rst_s_axi_aclk_57M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rfdc_ex_rst_s_axi_aclk_57M_0 || ORIG_REF_NAME==rfdc_ex_rst_s_axi_aclk_57M_0} -quiet] -quiet

# IP: bd/rfdc_ex/ip/rfdc_ex_clk_wiz_dac0_0/rfdc_ex_clk_wiz_dac0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rfdc_ex_clk_wiz_dac0_0 || ORIG_REF_NAME==rfdc_ex_clk_wiz_dac0_0} -quiet] -quiet

# IP: bd/rfdc_ex/ip/rfdc_ex_clk_wiz_adc0_0/rfdc_ex_clk_wiz_adc0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rfdc_ex_clk_wiz_adc0_0 || ORIG_REF_NAME==rfdc_ex_clk_wiz_adc0_0} -quiet] -quiet

# XDC: c:/Users/tommy/RfSoc/usp_rf_data_converter_0_ex/usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/rfdc_ex_ooc.xdc
