set_property SRC_FILE_INFO {cfile:c:/Users/tommy/RfSoc/usp_rf_data_converter_0_ex/imports/usp_rf_data_converter_0_example_design.xdc rfile:../../../imports/usp_rf_data_converter_0_example_design.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:70 export:INPUT save:INPUT read:READ} [current_design]
set_multicycle_path -to [get_pins -filter {REF_PIN_NAME== D} -of [get_cells -hier -filter {name =~ *usp_rf_data_converter_0_ex_i/ex_design/usp_rf_data_converter_0/inst/IP2Bus_Data_reg*}]] -setup 2
set_property src_info {type:XDC file:1 line:71 export:INPUT save:INPUT read:READ} [current_design]
set_multicycle_path -to [get_pins -filter {REF_PIN_NAME== D} -of [get_cells -hier -filter {name =~ *usp_rf_data_converter_0_ex_i/ex_design/usp_rf_data_converter_0/inst/IP2Bus_Data_reg*}]] -hold 1
set_property src_info {type:XDC file:1 line:80 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_cells -hier -regexp .*rf(?:da|ad)c_exdes_ctrl_i/(?:da|ad)c_exdes_cfg_i/.+num_samples_reg.*] -to [get_cells -hier -filter {name=~*dg_slice_00*addrb_reg[*]}]
set_property src_info {type:XDC file:1 line:81 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -user USP_RF_DATA_CONVERTER -type CDC -id CDC-1 -description "Number of samples register is a constant during normal operation" -from [list [get_pins -filter {REF_PIN_NAME=~*} -of [get_cells -hier -filter {name=~*c_exdes_cfg_i*num_samples_reg*}]]] -to   [list [get_pins -filter {REF_PIN_NAME==D} -of [get_cells -hier -filter {name=~*dg_slice_00*addrb_reg[*]}]]]
set_property src_info {type:XDC file:1 line:86 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_cells -hier -regexp .*rf(?:da|ad)c_exdes_ctrl_i/(?:da|ad)c_exdes_cfg_i/.+num_samples_reg.*] -to [get_cells -hier -filter name=~*dg_slice_00*addrbend_reg]
set_property src_info {type:XDC file:1 line:87 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -user USP_RF_DATA_CONVERTER -type CDC -id CDC-1 -description "Number of samples register is a constant during normal operation" -from [list [get_pins -filter {REF_PIN_NAME=~*} -of [get_cells -hier -filter {name=~*c_exdes_cfg_i*num_samples_reg*}]]] -to   [list [get_pins -filter {REF_PIN_NAME==D} -of [get_cells -hier -filter {name=~*dg_slice_00*addrbend_reg}]]]
set_property src_info {type:XDC file:1 line:93 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_cells -hier -regexp .*rf(?:da|ad)c_exdes_ctrl_i/(?:da|ad)c_exdes_cfg_i/.+num_samples_reg.*] -to [get_cells -hier -filter {name=~*ds_slice_10*addra_reg[*]}]
set_property src_info {type:XDC file:1 line:94 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -user USP_RF_DATA_CONVERTER -type CDC -id CDC-1 -description "Number of samples register is a constant during normal operation" -from [list [get_pins -filter {REF_PIN_NAME=~*} -of [get_cells -hier -filter {name=~*c_exdes_cfg_i*num_samples_reg*}]]] -to   [list [get_pins -filter {REF_PIN_NAME==D} -of [get_cells -hier -filter {name=~*ds_slice_10*addra_reg[*]}]]]
set_property src_info {type:XDC file:1 line:99 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_cells -hier -regexp .*rf(?:da|ad)c_exdes_ctrl_i/(?:da|ad)c_exdes_cfg_i/.+num_samples_reg.*] -to [get_cells -hier -filter name=~*ds_slice_10*working_i_reg]
set_property src_info {type:XDC file:1 line:100 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -user USP_RF_DATA_CONVERTER -type CDC -id CDC-1 -description "Number of samples register is a constant during normal operation" -from [list [get_pins -filter {REF_PIN_NAME=~*} -of [get_cells -hier -filter {name=~*c_exdes_cfg_i*num_samples_reg*}]]] -to   [list [get_pins -filter {REF_PIN_NAME==D} -of [get_cells -hier -filter {name=~*ds_slice_10*working_i_reg}]]]
set_property src_info {type:XDC file:1 line:105 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_cells -hier -regexp .*rf(?:da|ad)c_exdes_ctrl_i/(?:da|ad)c_exdes_cfg_i/.+num_samples_reg.*] -to [get_cells -hier -filter name=~*ds_slice_10*cap_complete_reg]
set_property src_info {type:XDC file:1 line:106 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -user USP_RF_DATA_CONVERTER -type CDC -id CDC-1 -description "Number of samples register is a constant during normal operation" -from [list [get_pins -filter {REF_PIN_NAME=~*} -of [get_cells -hier -filter {name=~*c_exdes_cfg_i*num_samples_reg*}]]] -to   [list [get_pins -filter {REF_PIN_NAME==D} -of [get_cells -hier -filter {name=~*ds_slice_10*cap_complete_reg}]]]
set_property src_info {type:XDC file:1 line:111 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_cells -hier -regexp .*rf(?:da|ad)c_exdes_ctrl_i/(?:da|ad)c_exdes_cfg_i/.+num_samples_reg.*] -to [get_cells -hier -filter name=~*ds_slice_10*wea_r_reg]
set_property src_info {type:XDC file:1 line:112 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -user USP_RF_DATA_CONVERTER -type CDC -id CDC-1 -description "Number of samples register is a constant during normal operation" -from [list [get_pins -filter {REF_PIN_NAME=~*} -of [get_cells -hier -filter {name=~*c_exdes_cfg_i*num_samples_reg*}]]] -to   [list [get_pins -filter {REF_PIN_NAME==D} -of [get_cells -hier -filter {name=~*ds_slice_10*wea_r_reg}]]]
