-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\radarSim4\Compare_To_Zero.vhd
-- Created: 2024-03-25 15:11:34
-- 
-- Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Compare_To_Zero
-- Source Path: radarSim4/radar/Compare To Zero
-- Hierarchy Level: 1
-- Model version: 1.37
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY Compare_To_Zero IS
  PORT( u                                 :   IN    std_logic_vector(23 DOWNTO 0);  -- sfix24_En8
        y                                 :   OUT   std_logic
        );
END Compare_To_Zero;


ARCHITECTURE rtl OF Compare_To_Zero IS

  -- Signals
  SIGNAL u_signed                         : signed(23 DOWNTO 0);  -- sfix24_En8
  SIGNAL Constant_out1                    : signed(23 DOWNTO 0);  -- sfix24_En8
  SIGNAL Compare_relop1                   : std_logic;

BEGIN
  u_signed <= signed(u);

  Constant_out1 <= to_signed(16#000000#, 24);

  
  Compare_relop1 <= '1' WHEN u_signed >= Constant_out1 ELSE
      '0';

  y <= Compare_relop1;

END rtl;

