open_system('radarSim4');
open_system('gm_radarSim4');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_radarSim4/radar/Compare To Zero/Compare', 'user1');
annotate_port('gm_radarSim4/radar/Compare To Zero/Compare', 0, 1, 'Blocks delay absorption: 2 cycles');
hilite_system('radarSim4/radar/Compare To Zero/Compare', 'user1');
annotate_port('radarSim4/radar/Compare To Zero/Compare', 0, 1, 'Blocks delay absorption: 2 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_radarSim4/radar/FreqMeasure/Maximum', 'user1');
annotate_port('gm_radarSim4/radar/FreqMeasure/Maximum', 0, 1, 'Blocks delay absorption: 102 cycles');
hilite_system('radarSim4/radar/FreqMeasure/Maximum', 'user1');
annotate_port('radarSim4/radar/FreqMeasure/Maximum', 0, 1, 'Blocks delay absorption: 102 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_radarSim4/radar/FreqMeasure/Maximum', 'user1');
annotate_port('gm_radarSim4/radar/FreqMeasure/Maximum', 0, 1, 'Blocks delay absorption: 102 cycles');
hilite_system('radarSim4/radar/FreqMeasure/Maximum', 'user1');
annotate_port('radarSim4/radar/FreqMeasure/Maximum', 0, 1, 'Blocks delay absorption: 102 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_radarSim4/radar/FreqMeasure1/Maximum', 'user1');
annotate_port('gm_radarSim4/radar/FreqMeasure1/Maximum', 0, 1, 'Blocks delay absorption: 102 cycles');
hilite_system('radarSim4/radar/FreqMeasure1/Maximum', 'user1');
annotate_port('radarSim4/radar/FreqMeasure1/Maximum', 0, 1, 'Blocks delay absorption: 102 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_radarSim4/radar/FreqMeasure1/Maximum', 'user1');
annotate_port('gm_radarSim4/radar/FreqMeasure1/Maximum', 0, 1, 'Blocks delay absorption: 102 cycles');
hilite_system('radarSim4/radar/FreqMeasure1/Maximum', 'user1');
annotate_port('radarSim4/radar/FreqMeasure1/Maximum', 0, 1, 'Blocks delay absorption: 102 cycles');
