-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\radarSim4\If_Action_Subsystem.vhd
-- Created: 2024-03-25 15:11:34
-- 
-- Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: If_Action_Subsystem
-- Source Path: radarSim4/radar/If Action Subsystem
-- Hierarchy Level: 1
-- Model version: 1.37
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY If_Action_Subsystem IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        In1                               :   IN    std_logic_vector(23 DOWNTO 0);  -- sfix24_En8
        Action_Port                       :   IN    std_logic;
        Out1                              :   OUT   std_logic_vector(23 DOWNTO 0)  -- sfix24_En8
        );
END If_Action_Subsystem;


ARCHITECTURE rtl OF If_Action_Subsystem IS

  -- Signals
  SIGNAL Action_Port_out2                 : std_logic;
  SIGNAL In1_signed                       : signed(23 DOWNTO 0);  -- sfix24_En8
  SIGNAL In1_bypass                       : signed(23 DOWNTO 0);  -- sfix24_En8
  SIGNAL In1_last_value                   : signed(23 DOWNTO 0);  -- sfix24_En8

BEGIN
  Action_Port_out2 <= Action_Port;

  In1_signed <= signed(In1);

  Out1_bypass_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        In1_last_value <= to_signed(16#000000#, 24);
      ELSIF enb = '1' THEN
        In1_last_value <= In1_bypass;
      END IF;
    END IF;
  END PROCESS Out1_bypass_process;


  
  In1_bypass <= In1_last_value WHEN Action_Port_out2 = '0' ELSE
      In1_signed;

  Out1 <= std_logic_vector(In1_bypass);

END rtl;

