-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\radarSim4\radar_pkg.vhd
-- Created: 2024-03-25 15:11:34
-- 
-- Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
-- 
-- -------------------------------------------------------------


LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

PACKAGE radar_pkg IS
  TYPE vector_of_std_logic_vector24 IS ARRAY (NATURAL RANGE <>) OF std_logic_vector(23 DOWNTO 0);
  TYPE vector_of_std_logic_vector31 IS ARRAY (NATURAL RANGE <>) OF std_logic_vector(30 DOWNTO 0);
  TYPE vector_of_signed31 IS ARRAY (NATURAL RANGE <>) OF signed(30 DOWNTO 0);
  TYPE vector_of_signed62 IS ARRAY (NATURAL RANGE <>) OF signed(61 DOWNTO 0);
  TYPE vector_of_signed63 IS ARRAY (NATURAL RANGE <>) OF signed(62 DOWNTO 0);
END radar_pkg;

